bkash/bkash/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('services/',include('services.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bkash/home/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('updateUser/', views.UpdateUserView.as_view(), name='updateUser'),
    path('userInfo/', views.UserInfoView.as_view(), name='userInfo'),
    path('addBranch/', views.addBranchView.as_view(), name='addBranch'),
    path('customerInfo/', views.customerInfoView.as_view(), name='customerInfo'),
    path('agentInfo/', views.agentInfoView.as_view(), name='agentInfo'),
    path('merchantInfo/', views.merchantInfoView.as_view(), name='merchantInfo'),
    path('operatorInfo/', views.operatorInfoView.as_view(), name='operatorInfo'),
    path('serviceInfo/', views.serviceProviderInfoView.as_view(), name='serviceInfo')
]

bkash/services/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'services'

urlpatterns = [
    path('sendMoney/',views.SendMoneyView.as_view(),name='sendMoney'),
    path('cashIn/',views.CashInView.as_view(),name='cashIn'),
    path('cashOut/',views.CashOutView.as_view(),name='cashOut'),
    path('payBill/',views.PayBillView.as_view(),name='payBill'),
    path('payBill/<int:service_id>/',views.PayBillView.as_view(),name='payBill'),
    path('history/',views.HistoryView.as_view(),name='history'),
    path('payment/', views.MerchantPaymentView.as_view(), name='merchantpayment'),
    path('recharge/', views.MobileRechargeView.as_view(), name='mobileRecharge')
]

bkash/home/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views import View
from .models import UserProfile, UpdateUser, AdminProfile, MerchantProfile, Branch, Offer, AllCustomerInfo, AllAgentInfo, AllMerchantInfo, AllOperatorInfo, AllServiceProviderInfo
from django.core.files.storage import FileSystemStorage
from dashboard.models import execute_sql,connection
import os
# Create your views here.


class HomeView(View):
    def get(self, request):
        if request.session.get('CUSTOMER'):
            if not (request.COOKIES.get('NAME') and request.COOKIES.get('PHOTO') and request.COOKIES.get('MOBILE')):
                user = UserProfile(request.session.get('CUSTOMER'))
                context = user.getProfile()
                context['TYPE'] = 'customer'
                sql = 'SELECT CUSTOMER_BALANCE FROM CUSTOMER WHERE CUSTOMER_ID=:cust'
                balance = execute_sql(
                    sql, [request.session.get('CUSTOMER')], False, True,connection)[0][0]
                context['BALANCE'] = balance

                context['MERCHANT'] = getMerchant()

                resp = render(request, 'home/user_home.html', context)
                resp.set_cookie('NAME', context['NAME'])
                resp.set_cookie('MOBILE', context['MOBILE'])
                resp.set_cookie('PHOTO', context['PHOTO'])
                return resp

            sql = 'SELECT CUSTOMER_BALANCE FROM CUSTOMER WHERE CUSTOMER_ID=:cust'
            balance = execute_sql(
                sql, [request.session.get('CUSTOMER')], False, True,connection)[0][0]

            context = {'NAME': request.COOKIES.get('NAME'), 'PHOTO': request.COOKIES.get('PHOTO'),
                       'MOBILE': request.COOKIES.get('MOBILE'), 'TYPE': 'customer', 'BALANCE': balance}
            context['MERCHANT'] = getMerchant()
            return render(request, 'home/user_home.html', context)

        elif request.session.get('AGENT'):
            if not (request.COOKIES.get('NAME') and request.COOKIES.get('PHOTO') and request.COOKIES.get('MOBILE')):
                user = UserProfile(request.session.get('AGENT'))
                context = user.getProfile()
                context['TYPE'] = 'agent'
                sql = 'SELECT AGENT_BALANCE FROM AGENT WHERE AGENT_ID=:agent'
                balance = execute_sql(
                    sql, [request.session.get('AGENT')], False, True,connection)[0][0]
                context['BALANCE'] = balance
                context['MERCHANT'] = getMerchant()
                resp = render(request, 'home/user_home.html', context)
                resp.set_cookie('NAME', context['NAME'])
                resp.set_cookie('MOBILE', context['MOBILE'])
                resp.set_cookie('PHOTO', context['PHOTO'])
                return resp

            sql = 'SELECT AGENT_BALANCE FROM AGENT WHERE AGENT_ID=:agent'
            balance = execute_sql(
                sql, [request.session.get('AGENT')], False, True,connection)[0][0]

            context = {'NAME': request.COOKIES.get('NAME'), 'PHOTO': request.COOKIES.get('PHOTO'),
                       'MOBILE': request.COOKIES.get('MOBILE'), 'TYPE': 'agent', 'BALANCE': balance}
            context['MERCHANT'] = getMerchant()
            return render(request, 'home/user_home.html', context)

        elif request.session.get('ADMIN'):
            #context = {'NAME':request.COOKIES.get('NAME'),'CUSTOMER':request.COOKIES.get('CUSTOMER')}
            user = AdminProfile(request.session.get('ADMIN'))
            context = user.getProfile()
            return render(request, 'home/admin_home.html', context)

        elif request.session.get('MERCHANT'):
            if not (request.COOKIES.get('NAME') and request.COOKIES.get('PHOTO') and request.COOKIES.get('TRADE_LICENSE_NO') and request.COOKIES.get('HEAD_OFFICE_LOCATION') and request.COOKIES.get('BRANCH') and request.cookies.get('OFFER_PERCENT')):
                merchant = MerchantProfile(request.session.get('MERCHANT'))
                context = merchant.getProfile()
                context['TYPE'] = 'merchant'
                resp = render(request, 'home/merchant_home.html', context)
                resp.set_cookie('NAME', context['NAME'])
                resp.set_cookie('PHOTO', context['PHOTO'])
                resp.set_cookie('TRADE_LICENSE_NO',
                                context['TRADE_LICENSE_NO'])
                resp.set_cookie('HEAD_OFFICE_LOCATION',
                                context['HEAD_OFFICE_LOCATION'])
                resp.set_cookie('BRANCH_NAME', context['BRANCH'])
                resp.set_cookie('OFFER_PERCENT', context['OFFER_PERCENT'])
                return resp

            context = {'NAME': request.COOKIES.get('NAME'), 'PHOTO': request.COOKIES.get('PHOTO'),
                       'TRADE_LICENSE_NO': request.COOKIES.get('TRADE_LICENSE_NO'), 'TYPE': 'merchant',
                       'HEAD_OFFICE_LOCATION': request.COOKIES.get('HEAD_OFFICE_LOCATION'),
                       'BRANCH': request.COOKIES.get('BRANCH_NAME'), 'OFFER_PERCENT': request.COOKIES.get('OFFER_PERCENT')}
            return render(request, 'home/merchant_home.html', context)

        return render(request, 'home/home.html')

    def post(self, request):
        if request.session.get('ADMIN'):
            admin_id = request.session.get('ADMIN')
            if request.POST.get('agent_mobile_no') and request.POST.get('add_money_amount'):
                agent_number = request.POST.get('agent_mobile_no')
                amount = request.POST.get('add_money_amount')
                admin = AdminProfile(admin_id)
                if admin.addMoney(agent_number, amount):
                    add_money_successful = True
                    context = admin.getProfile()
                    context['add_money_successful'] = add_money_successful
                    return render(request, 'home/admin_home.html', context)
                else:
                    add_money_failed = True
                    context = admin.getProfile()
                    context['add_money_failed'] = add_money_failed
                    return render(request, 'home/admin_home.html', context)
            else:
                for name, key in request.POST.items():
                    if name[0:4] == 'CUST':
                        if int(key) > 0:
                            sql = 'UPDATE CUSTOMER SET APPROVED_BY=:admin WHERE CUSTOMER_ID=:cust'
                            list = [request.session.get('ADMIN'), key]
                            execute_sql(sql, list, True, False,connection)
                        elif int(key) < 0:
                            sql = 'DELETE CUSTOMER WHERE CUSTOMER_ID=:cust'
                            list = [-int(key)]
                            execute_sql(sql, list, True, False,connection)
                            sql = 'DELETE USERS WHERE USER_ID=:user'
                            execute_sql(sql, list, True, False,connection)
                    elif name[0:4] == 'AGEN':
                        if int(key) > 0:
                            sql = 'UPDATE AGENT SET APPROVED_BY=:admin WHERE AGENT_ID=:agent'
                            list = [request.session.get('ADMIN'), key]
                            execute_sql(sql, list, True, False,connection)
                            sql = 'UPDATE AGENT SET AGENT_BALANCE=5000 WHERE AGENT_ID=:agent'
                            list = [key]
                            execute_sql(sql, list, True, False,connection)
                        elif int(key) < 0:
                            sql = 'DELETE AGENT WHERE AGENT_ID=:admin'
                            list = [-int(key)]
                            execute_sql(sql, list, True, False,connection)
                            sql = 'DELETE USERS WHERE USER_ID=:user'
                            execute_sql(sql, list, True, False,connection)
                    elif name[0:4] == 'ADMI':
                        if int(key) > 0:
                            sql = 'UPDATE ADMIN SET APPROVED_BY=:admin WHERE ADMIN_ID=:admin'
                            list = [request.session.get('ADMIN'), key]
                            execute_sql(sql, list, True, False,connection)
                        elif int(key) < 0:
                            sql = 'DELETE ADMIN WHERE ADMIN_ID=:admin'
                            list = [-int(key)]
                            execute_sql(sql, list, True, False,connection)
                    elif name[0:4] == 'MERC':
                        if int(key) > 0:
                            sql = 'UPDATE MERCHANTS SET APPROVED_BY=:admin WHERE MERCHANT_ID=:merchant'
                            list = [request.session.get('ADMIN'), key]
                            execute_sql(sql, list, True, False,connection)
                        elif int(key) < 0:
                            sql = 'DELETE MERCHANTS WHERE MERCHANT_ID=:merchant'
                            list = [-int(key)]
                            execute_sql(sql, list, True, False,connection)
                    elif name[0:4] == 'SERV':
                        if int(key) > 0:
                            sql = 'UPDATE UTILITY_SERVICE SET APPROVED_BY=:admin WHERE SERVICE_ID=:service'
                            list = [request.session.get('ADMIN'), key]
                            execute_sql(sql, list, True, False,connection)
                        elif int(key) < 0:
                            sql = 'DELETE UTILITY_SERVICE WHERE SERVICE_ID=:service'
                            list = [-int(key)]
                            execute_sql(sql, list, True, False,connection)
                    elif name[0:4] == 'OPER':
                        if int(key) > 0:
                            sql = 'UPDATE MOBILE_OPERATOR SET APPROVED_BY=:admin WHERE OPERATOR_ID=:operator'
                            list = [request.session.get('ADMIN'), key]
                            execute_sql(sql, list, True, False,connection)
                        elif int(key) < 0:

bkash/home/templates/home/admin_merchant_info.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <script
      src="https://kit.fontawesome.com/e367819fd5.js"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <title>Merchant Info</title>
    <style>
      p {
        font-weight: 500;
      }
      td {
        font-weight: 500;
      }
      footer {
        background-color: #3f3f3f;
        color: #d5d5d5;
        padding-top: 2rem;
      }
      hr.light {
        border-top: 1px solid #d5d5d5;
        width: 75%;
        margin-top: 0.8rem;
        margin-bottom: 1rem;
      }
      hr.light-100 {
        border-top: 1px solid #d5d5d5;
        width: 100%;
        margin-top: 0.8rem;
        margin-bottom: 1rem;
      }
      .table-sticky th {
        background: rgb(28, 200, 212);
        position: sticky;
        top: -1px;
        z-index: 990;
      }
      .navbar {
        padding: 15px 10px;
        background: #fff;
        border: none;
        border-radius: 0;
        margin-bottom: 40px;
        box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.1);
      }
      .navbar-btn {
        box-shadow: none;
        outline: none !important;
        border: none;
      }
    </style>
  </head>
  <body>
    <div class="content">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="" class="navbar-brand"
          ><img
            src="{% static 'home/img/icon.png' %}"
            alt=""
            style="max-width: 50%; max-height: 50%; object-fit: contain"
            class="px-3"
        /></a>

        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item pl-2">
              <h3 class="d-inline-block text-right px-2">Admin</h3>
            </li>
            <li class="nav-item pr-2">
              <i
                class="fas fa-user-secret fa-2x d-inline-block text-right px-2"
              ></i>
            </li>
            <li class="nav-item px-2">
              <a href="{% url 'home:home' %}" class="btn btn-primary"
                >Back To Home</a
              >
            </li>
          </ul>
        </div>
      </nav>

      <div class="content-wrapper">
        <div class="card my-4">
          <div class="card-header text-center">
            <i
              class="fas fa-warehouse fa-2x d-inline-block text-right px-2"
              style="color: rgb(24, 85, 5)"
            ></i>
            <h5 class="d-inline-block align-middle">
              Merchants Registered In The System
            </h5>
          </div>
          {% if MERCHANT %}
          <div class="card-body">
            <table class="table table-bordered table-hover table-sticky">
              <thead style="background-color: rgba(115, 218, 32, 0.781)">
                <tr class="text-center">
                  <th scope="col">Photo</th>
                  <th scope="col">Merchant Name</th>
                  <th scope="col">Trade License</th>
                  <th scope="col">Head Office Location</th>
                  <th scope="col">Cuurent Offer</th>
                  <th scope="col">Total Branch</th>
                  <th scope="col">Total Balance</th>
                  <th scope="col">Transaction(Last 30 days)</th>
                </tr>
              </thead>
              <tbody>
                {% for mer in MERCHANT %}
                <tr>
                  <td class="align-middle text-center">
                    <img
                      src="..\media\{{mer.merchant_photo}}?lastmod=12345678"
                      alt=""
                      width="100"
                      height="100"
                      style="object-fit: contain"
                      class="mr-3 rounded-circle img-thumbnail shadow-sm"
                    />
                  </td>
                  <td class="align-middle text-center">
                    {{mer.merchant_name}}
                  </td>
                  <td class="align-middle text-center">
                    {{mer.trade_license}}
                  </td>
                  <td class="align-middle text-center">{{mer.head_office}}</td>
                  <td class="align-middle text-center">{{mer.offer}}</td>
                  <td class="align-middle text-center">{{mer.total_branch}}</td>
                  <td class="align-middle text-center">{{mer.mer_balance}}</td>
                  <td class="align-middle text-center">
                    {{mer.total_transaction}}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          {% endif %}
        </div>
      </div>

      <footer id="contact">
        <div class="container-fluid padding">
          <div class="row text-center">
            <div class="col-12">
              <h3>Contact Us</h3>
            </div>
            <div class="col-md-4">
              <hr class="light" />
              <i class="fas fa-phone mb-2"></i>
              <h5>Mobile Number</h5>
              <hr class="light" />
              <p>+8801771369217</p>
              <p>+8801521103929</p>
            </div>
            <div class="col-md-4">
              <hr class="light" />
              <i class="fas fa-laptop-house mb-2"></i>
              <h5>Location</h5>
              <hr class="light" />
              <p>Room No : 219</p>
              <p>Ahsanullah Hall</p>
              <p>BUET,Dhaka</p>
            </div>
            <div class="col-md-4">
              <hr class="light" />
              <i class="far fa-envelope mb-2"></i>
              <h5>Email</h5>
              <hr class="light" />
              <p>asifahmedutsa@gmail.com</p>
              <p>abdullahalnoman@gmail.com</p>
            </div>
            <div class="col-12">
              <hr class="light-100" />
              <h5>copyright&copy;bKash.com</h5>
            </div>
          </div>
        </div>
      </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>
</html>

bkash/home/templates/home/user_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'home/css/homestyle.css' %}" />
    <script
      src="https://kit.fontawesome.com/e367819fd5.js"
      crossorigin="anonymous"
    ></script>

    <title>bootstrap 4 sidebar</title>
  </head>

  <body>
    {% if MOBILE %}
    <div class="wrapper">
      <nav id="sidebar">
        <div class="sidebar-header">
          <!--<h3>BOOTSTRAP SIDEBAR</h3>-->
          <div class="py-4 px-2 mb-4">
            <div class="media d-flex align-items-center justify-content-center">
              <img
                src="{{PHOTO}}?lastmod=12345678"
                alt=""
                width="100"
                height="100"
                class="mr-3 rounded-circle img-thumbnail shadow-sm"
              />
              <div class="media-body">
                <h5 class="m-0">{{NAME}}</h5>
                {% if TYPE == 'customer' %}
                <p class="font-weight-normal text-white mb-0">Customer</p>
                {% elif TYPE == 'agent' %}
                <p class="font-weight-normal text-white mb-0">Agent</p>
                {% endif %}
              </div>
            </div>
            <p class="float-left text-white mb-0">Mobile: {{MOBILE}}</p>
          </div>
        </div>

        <ul class="list-unstyled components">
          <li>
            <a
              href="#balanceSubmenu"
              data-toggle="collapse"
              aria-expanded="false"
              class="dropdown-toggle"
              >Click For Balance</a
            >
            <ul class="collapse list-unstyled" id="balanceSubmenu">
              <li class="text-center">
                <p
                  class="pb-1 font-weight-bold"
                  style="color: rgb(235, 140, 16)"
                >
                  {{BALANCE}} <i class="fas fa-dollar-sign"></i>
                </p>
              </li>
            </ul>
          </li>
          <li>
            <a href="{% url 'home:home' %}">Home</a>
          </li>
          <li>
            <a
              href="#pageSubmenu"
              data-toggle="collapse"
              aria-expanded="false"
              class="dropdown-toggle"
              >Profile</a
            >
            <ul class="collapse list-unstyled" id="pageSubmenu">
              <li>
                <a href="{% url 'home:userInfo' %}">View Profile</a>
              </li>
              <li>
                <a href="{% url 'home:updateUser' %}">Change Info</a>
              </li>
            </ul>
          </li>
          <li>
            <a href="{% url 'services:history' %}">Transaction History</a>
          </li>
          <li>
            <a href="#contact">Contact Us</a>
          </li>
        </ul>

        <ul class="list-unstyled CTAs">
          <li>
            <a href="{% url 'home:logout' %}" class="download">Logout</a>
          </li>
        </ul>
      </nav>

      <div class="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
          <button type="button" id="sidebarCollapse" class="btn btn-info">
            <i class="fa fa-align-justify"></i>
          </button>
          <a href="" class="navbar-brand"
            ><img
              src="{% static 'home/img/icon.png' %}"
              alt=""
              style="max-width: 50%; max-height: 50%; object-fit: contain"
              class="px-3"
          /></a>

          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <div
                  class="media d-flex align-items-center justify-content-center"
                >
                  <a href="" class="nav-link">
                    <img
                      src="{{PHOTO}}?lastmod=12345678"
                      alt=""
                      width="50"
                      height="50"
                      style="object-fit: contain"
                      class="mr-3 rounded-circle img-thumbnail shadow-sm"
                    />
                  </a>
                </div>
              </li>
            </ul>
          </div>
        </nav>

        <div class="content-wrapper">
          <div class="container-fluid padding">
            <div class="row welcome text-center">
              <div class="col-12">
                <h1 class="display-4">Safe Money Transfer</h1>
              </div>
              <hr />
              <div class="col-12">
                <p class="lead">
                  Welcome to our online money transaction website bKash.You can
                  do Send Money,Cash In,Cash Out,Mobile Recharge,Shopping
                  Payment and Paying Differents Bills through our website.
                </p>
              </div>
            </div>
          </div>

          <!--- Three Column Section -->
          <div class="container-fluid padding">
            <div class="row text-center padding">
              <div class="col-xs-12 col-sm-6 col-md-4 my-2">
                <div class="card">
                  <div class="card-body">
                    <i class="fas fa-shopping-bag"></i>
                    <h3>Payment</h3>
                    <p>Shopping Payment with CashBack</p>
                    <a
                      href="{% url 'services:merchantpayment' %}"
                      class="btn btn-primary"
                      >Make Payment</a
                    >
                  </div>
                </div>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-4 my-2">
                <div class="card">
                  <div class="card-body">
                    <i class="far fa-lightbulb"></i>
                    <h3>Bill</h3>
                    <p>Pay Your gas,electricity bill</p>
                    <a
                      href="{% url 'services:payBill' %}"
                      class="btn btn-primary"
                      >Pay Bill</a
                    >
                  </div>
                </div>
              </div>

              <div class="col-xs-12 col-sm-6 col-md-4 my-2">
                <div class="card">
                  <div class="card-body">
                    <i class="fas fa-mobile-alt"></i>
                    <h3>Mobile Recharge</h3>
                    <p>Recharge Your Mobile Number</p>
                    <a
                      href="{% url 'services:mobileRecharge' %}"
                      class="btn btn-primary"
                      >Recharge</a
                    >
                  </div>
                </div>
              </div>

              {% if TYPE == 'customer' %}
              <div class="col-xs-12 col-sm-6 col-md-4 my-2">
                <div class="card">
                  <div class="card-body">
                    <i class="fas fa-comments-dollar"></i>
                    <h3>Send Money</h3>
                    <p>Send Money To other Customer</p>
                    <a
                      href="{% url 'services:sendMoney' %}"
                      class="btn btn-primary"
                      >Send Money</a
                    >
                  </div>
                </div>
              </div>

              <div class="col-xs-12 col-sm-6 col-md-4 my-2">
                <div class="card">
                  <div class="card-body">
                    <i class="fas fa-hand-holding-usd"></i>
                    <h3>Cash Out</h3>
                    <p>Take Out Money From Your Account</p>
                    <a
                      href="{% url 'services:cashOut' %}"
                      class="btn btn-primary"
                      >Cash Out</a
                    >
                  </div>
                </div>
              </div>
            {% elif TYPE == 'agent'%}
            <div class="col-xs-12 col-sm-6 col-md-4 my-2">
              <div class="card">
                <div class="card-body">
                  <i class="fas fa-funnel-dollar"></i>
                  <h3>Cash In</h3>
                  <p>Add Money To Your Account</p>
                  <a href="{% url 'services:cashIn' %}" class="btn btn-primary"
                    >Cash In</a
                  >
                </div>
              </div>
            </div>
            {% endif %}

        </div>

            <hr class="my-4" />
            <h2 class="text-center d-block">Merchants With Cashback Offer</h2>
            {% if MERCHANT %}
            <div class="container-fluid" style="overflow-x: auto">
              <div class="row flex-nowrap mt-4">
                {% for merchant in MERCHANT %}
                <div class="col-4">
                  <div class="card card-block text-center">
                    <div
                      class="media d-flex align-items-center justify-content-center"
                    >
                      <a href="" class="nav-link">
                        <img
                          src="media\{{merchant.merchant_photo}}?lastmod=12345678"
                          alt=""
                          width="100"
                          height="100"
                          style="object-fit: contain"
                          class="mr-3 rounded-circle img-thumbnail shadow-sm"
                        />
                      </a>
                    </div>
                    <p class="font-weight-bold text-dark">{{merchant.merchant_name}}</p>
                    <p class="font-weight-bold text-dark">{{merchant.discount_percent}}% Cash Back</p>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          {% endif %}
        </div>
      </div>

      <footer id="contact">
        <div class="container-fluid padding">
          <div class="row text-center">
            <div class="col-12">
              <h3>Contact Us</h3>
            </div>
            <div class="col-md-4">
              <hr class="light" />
              <i class="fas fa-phone mb-2"></i>
              <h5>Mobile Number</h5>
              <hr class="light" />
              <p>+8801771369217</p>
              <p>+8801521103929</p>
            </div>
            <div class="col-md-4">
              <hr class="light" />
              <i class="fas fa-laptop-house mb-2"></i>
              <h5>Location</h5>
              <hr class="light" />
              <p>Room No : 219</p>
              <p>Ahsanullah Hall</p>
              <p>BUET,Dhaka</p>
            </div>
            <div class="col-md-4">
              <hr class="light" />
              <i class="far fa-envelope mb-2"></i>
              <h5>Email</h5>
              <hr class="light" />
              <p>asifahmedutsa@gmail.com</p>
              <p>abdullahalnoman@gmail.com</p>
            </div>
            <div class="col-12">
              <hr class="light-100" />
              <h5>copyright&copy;bKash.com</h5>
            </div>
          </div>
        </div>
      </footer>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script>
      $(document).ready(function () {
        $("#sidebarCollapse").on("click", function () {
          $("#sidebar").toggleClass("active");
        });
      });
    </script>

    {% endif %}
  </body>
</html>