bkash/bkash/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('services/',include('services.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bkash/home/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('updateUser/', views.UpdateUserView.as_view(), name='updateUser'),
    path('userInfo/', views.UserInfoView.as_view(), name='userInfo'),
    path('addBranch/', views.addBranchView.as_view(), name='addBranch'),
    path('customerInfo/', views.customerInfoView.as_view(), name='customerInfo'),
    path('agentInfo/', views.agentInfoView.as_view(), name='agentInfo'),
    path('merchantInfo/', views.merchantInfoView.as_view(), name='merchantInfo'),
    path('operatorInfo/', views.operatorInfoView.as_view(), name='operatorInfo'),
    path('serviceInfo/', views.serviceProviderInfoView.as_view(), name='serviceInfo')
]

bkash/services/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'services'

urlpatterns = [
    path('sendMoney/',views.SendMoneyView.as_view(),name='sendMoney'),
    path('cashIn/',views.CashInView.as_view(),name='cashIn'),
    path('cashOut/',views.CashOutView.as_view(),name='cashOut'),
    path('payBill/',views.PayBillView.as_view(),name='payBill'),
    path('payBill/<int:service_id>/',views.PayBillView.as_view(),name='payBill'),
    path('history/',views.HistoryView.as_view(),name='history'),
    path('payment/', views.MerchantPaymentView.as_view(), name='merchantpayment'),
    path('recharge/', views.MobileRechargeView.as_view(), name='mobileRecharge')
]

bkash/services/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views import View
from .models import SendMoney,CashIn,CashOut,HistoryOf,PayBill, MerchantPayment,MobileRecharge
from dashboard.models import execute_sql,connection
from django.http import Http404


class SendMoneyView(View):
    def get(self, request):
        if request.session.get('CUSTOMER'):
            return render(request, 'services/sendMoney.html')

    def post(self, request):
        reciver_mobile_no = request.POST.get('to_mobile_no')
        sender_id = request.session.get('CUSTOMER')
        amount = int(request.POST.get('amount'))

        trans_failed = False
        send_money_trans = SendMoney(
            sender_id, reciver_mobile_no, amount, request.POST.get('password'))
        if send_money_trans.validMobileNo() and send_money_trans.hasEnoughMoney() and send_money_trans.isCorrectPass():
            send_money_trans.doTransiction()
            return redirect('services:history')
        else:
            trans_failed = True
            return render(request, 'services/sendMoney.html', {'message': trans_failed})

        return render(request, 'services/sendMoney.html', {'message': trans_failed})


class CashInView(View):
    def get(self, request):
        if request.session.get('AGENT'):
            return render(request, 'services/cashIn.html')

    def post(self, request):
        reciver_mobile_no = request.POST.get('to_mobile_no')
        sender_id = request.session.get('AGENT')
        amount = int(request.POST.get('amount'))

        trans_failed = False
        cash_in_trans = CashIn(sender_id, reciver_mobile_no,
                               amount, request.POST.get('password'))
        if cash_in_trans.validMobileNo() and cash_in_trans.hasEnoughMoney() and cash_in_trans.isCorrectPass():
            cash_in_trans.doTransiction()
            return redirect('services:history')
        else:
            trans_failed = True
            return render(request, 'services/cashIn.html', {'message': trans_failed})

        return render(request, 'services/cashIn.html', {'message': trans_failed})


class CashOutView(View):
    def get(self, request):
        if request.session.get('CUSTOMER'):
            return render(request, 'services/cashOut.html')

    def post(self, request):
        reciver_mobile_no = request.POST.get('to_mobile_no')
        sender_id = request.session.get('CUSTOMER')
        amount = int(request.POST.get('amount'))

        trans_failed = False
        cash_out_trans = CashOut(
            sender_id, reciver_mobile_no, amount, request.POST.get('password'))
        if cash_out_trans.validMobileNo() and cash_out_trans.hasEnoughMoney() and cash_out_trans.isCorrectPass():
            cash_out_trans.doTransiction()
            return redirect('services:history')
        else:
            trans_failed = True
            return render(request, 'services/cashOut.html', {'message': trans_failed})

        return render(request, 'services/cashOut.html', {'message': trans_failed})


class PayBillView(View):
    def get(self, request, service_id=0):
        if (request.session.get('CUSTOMER') or request.session.get('AGENT')) and service_id == 0:
            return render(request, 'services/payBill.html', {'PHOTO':request.COOKIES.get('PHOTO')})
        elif request.session.get('CUSTOMER') or request.session.get('AGENT'):
            context = PayBill().serviceOfID(service_id)
            context['PHOTO'] = request.COOKIES.get('PHOTO')
            return render(request, 'services/payBillForm.html', context)
        else:
            return Http404('Wrong Info')

    def post(self, request, service_id=0):
        if (request.session.get('CUSTOMER') or request.session.get('AGENT')) and service_id == 0:
            serviceChoice = request.POST.get('choice')
            services = PayBill()
            context = services.servicesOfType(serviceChoice)
            return render(request, 'services/payBill.html', context)
        elif request.session.get('CUSTOMER') or request.session.get('AGENT'):
            if request.session.get('CUSTOMER'):
                user_id = request.session.get('CUSTOMER')
                billing_id = request.POST.get('billing_id')
                amount = request.POST.get('amount')
                password = request.POST.get('password')

                if PayBill().isCorrectPass(True, user_id, password) and PayBill().hasEnoughMoney(True, user_id, amount):
                    PayBill().doTransictionCustomer(service_id, user_id, amount, billing_id)
                    return redirect('services:history')
            elif request.session.get('AGENT'):
                user_id = request.session.get('AGENT')
                billing_id = request.POST.get('billing_id')
                amount = int(request.POST.get('amount'))
                password = request.POST.get('password')

                if PayBill().isCorrectPass(False, user_id, password) and PayBill().hasEnoughMoney(False, user_id, amount):
                    PayBill().doTransictionAgent(service_id, user_id, amount, billing_id)
                    return redirect('services:history')
        else:
            return Http404('Wrong Info')


class HistoryView(View):
    def get(self, request):
        sender = 0
        if request.session.get('CUSTOMER'):
            sender= 'USER_' + str(request.session.get('CUSTOMER'))
            sql='SELECT CUSTOMER_BALANCE FROM CUSTOMER WHERE CUSTOMER_ID=:cust'
            balance = execute_sql(sql,[request.session.get('CUSTOMER')],False,True,connection)[0][0]

            context = {'NAME': request.COOKIES.get('NAME'), 'PHOTO': request.COOKIES.get('PHOTO'),
                       'MOBILE': request.COOKIES.get('MOBILE'), 'TYPE': 'customer', 'BALANCE': balance}
        elif request.session.get('AGENT'):
            sender= 'USER_' + str(request.session.get('AGENT'))
            sql='SELECT AGENT_BALANCE FROM AGENT WHERE AGENT_ID=:agent'
            balance = execute_sql(sql,[request.session.get('AGENT')],False,True,connection)[0][0]

            context = {'NAME': request.COOKIES.get('NAME'), 'PHOTO': request.COOKIES.get('PHOTO'),
                       'MOBILE': request.COOKIES.get('MOBILE'), 'TYPE': 'agent', 'BALANCE': balance}
        elif request.session.get('MERCHANT'):
            sender = request.session.get('MERCHANT')
            context = {'NAME': request.COOKIES.get('NAME'), 'PHOTO': request.COOKIES.get('PHOTO'),
                       'TRADE_LICENSE_NO': request.COOKIES.get('TRADE_LICENSE_NO'), 'TYPE': 'merchant',
                       'HEAD_OFFICE_LOCATION': request.COOKIES.get('HEAD_OFFICE_LOCATION'),
                       'BRANCH': request.COOKIES.get('BRANCH_NAME'), 'OFFER_PERCENT': request.COOKIES.get('OFFER_PERCENT')}

            sql = 'SELECT BRANCH_NAME,BRANCH_ID FROM BRANCH WHERE BRANCH_MERCHANT_ID=:id'
            ans = execute_sql(sql,[sender],False,True,connection)
            cont_mar_his = ans
            i = 0
            for x in ans:
                cont_mar_his[i] = {'NAME_BRANCH': x[0], 'BRANCH_HIS': HistoryOf(
                    'MERC_'+str(x[1])).getHistory()}
                i = i+1
            context['HISTORY'] = cont_mar_his
            return render(request, 'services/historyMerchant.html', context)
        else:
            return Http404('Not verified user')

        history = HistoryOf(sender)
        context['HISTORY'] = history.getHistory()

        return render(request, 'services/history.html', context)


class MerchantPaymentView(View):
    def get(self, request):
        return render(request, 'services/merchantPayment.html')

    def post(self, request):
        if request.session.get('CUSTOMER'):
            sender_id = request.session.get('CUSTOMER')
            sender_type = "customer"
        elif request.session.get('AGENT'):
            sender_id = request.session.get('AGENT')
            sender_type = "agent"

        merchant_mobile_no = request.POST.get('merchant_mobile_no')
        amount = int(request.POST.get('amount'))
        password = request.POST.get('password')

        merchant_payment_trans = MerchantPayment(
            sender_id, merchant_mobile_no, amount, password, sender_type)
        merchant_payment_failed = False
        if merchant_payment_trans.valid_merchant_mobile_no() and merchant_payment_trans.hasEnoughMoney() and merchant_payment_trans.is_correct_password():
            merchant_payment_trans.do_payment_transaction()
            return redirect('services:history')
        else:
            merchant_payment_failed = True
            return render(request, 'services/merchantPayment.html', {'message': merchant_payment_failed})

        return render(request, 'services/merchantPayment.html', {'message': merchant_payment_failed})


class MobileRechargeView(View):
    def get(self, request):
        return render(request, 'services/rechargeMobile.html')

    def post(self, request):
        if request.session.get('CUSTOMER'):
            sender_id = request.session.get('CUSTOMER')
            sender_type = "customer"
        elif request.session.get('AGENT'):
            sender_id = request.session.get('AGENT')
            sender_type = "agent"

        receiver_mobile_no = request.POST.get('to_mobile_no')
        recharge_amount = int(request.POST.get('amount'))
        password = request.POST.get('password')

        mobile_recharge_trans = MobileRecharge(
            sender_id, receiver_mobile_no, recharge_amount, password, sender_type)
        if mobile_recharge_trans.isOperatorAvailable() and mobile_recharge_trans.hasEnoughMoney() and mobile_recharge_trans.is_correct_password():
            mobile_recharge_trans.make_recharge()
            return redirect('services:history')
        else:
            mobile_recharge_failed = True
            return render(request, 'services/rechargeMobile.html', {'message': mobile_recharge_failed})

bkash/services/templates/services/genericBlock.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'home/css/homestyle.css' %}" />
    <script src="https://kit.fontawesome.com/e367819fd5.js" crossorigin="anonymous"></script>
    <script>
    function submitform()
    {
    document.getElementById("myForm").submit();
    }
    </script>
    <title>bootstrap 4 sidebar</title>
</head>

<body>
{% if MOBILE %}
    <div class="wrapper">
        <nav id="sidebar">
            <div class="sidebar-header">
                <!--<h3>BOOTSTRAP SIDEBAR</h3>-->
                <div class="py-4 px-2 mb-4">
                    <div class="media d-flex align-items-center justify-content-center">
                        <img src="../../{{PHOTO}}?lastmod=12345678" alt="" width="100" height="100"
                            class="mr-3 rounded-circle img-thumbnail shadow-sm" />
                        <div class="media-body">
                            <h5 class="m-0">{{NAME}}</h5>
                            {% if TYPE == 'customer' %}
                                <p class="font-weight-normal text-white mb-0">Customer</p>
                            {% elif TYPE == 'agent' %}
                                <p class="font-weight-normal text-white mb-0">Agent</p>
                            {% endif %}
                        </div>
                    </div>
                    <p class="float-left text-white mb-0">Mobile: {{MOBILE}}</p>
                   
                </div>
            </div>

            <ul class="list-unstyled components">
                <li>
                    <a
                      href="#balanceSubmenu"
                      data-toggle="collapse"
                      aria-expanded="false"
                      class="dropdown-toggle"
                      >Click For Balance</a
                    >
                    <ul class="collapse list-unstyled" id="balanceSubmenu">
                      <li class="text-center">
                        <p
                          class="pb-1 font-weight-bold"
                          style="color: rgb(235, 140, 16)"
                        >
                          {{BALANCE}} <i class="fas fa-dollar-sign"></i>
                        </p>
                      </li>
                    </ul>
                  </li>
                <li>
                    <a href="{% url 'home:home' %}">Home</a>
                </li>
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Profile</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="{% url 'home:userInfo' %}">View Profile</a>
                        </li>
                        <li>
                            <a href="{% url 'home:updateUser' %}">Change Info</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'services:history' %}">Transaction History</a>
                </li>
                <li>
                    <a href="#contact">Contact Us</a>
                </li>
            </ul>

            <ul class="list-unstyled CTAs">
                <li>
                    <a href="{% url 'home:logout' %}" class="download">Logout</a>
                </li>
            </ul>
        </nav>

        <div class="content">
            <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
                <button type="button" id="sidebarCollapse" class="btn btn-info">
                    <i class="fa fa-align-justify"></i>
                </button>
                <a href="" class="navbar-brand"><img src="{% static 'home/img/icon.png' %}" alt=""
                        style="max-width: 50%; max-height: 50%; object-fit: contain" class="px-3" /></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <div
                              class="media d-flex align-items-center justify-content-center"
                            >
                              <a href="" class="nav-link">
                                <img
                                  src="../../{{PHOTO}}"
                                  alt=""
                                  width="50"
                                  height="50"
                                  style="object-fit: contain"
                                  class="mr-3 rounded-circle img-thumbnail shadow-sm"
                                />
                              </a>
                            </div>
                          </li>
                    </ul>
                </div>
            </nav>

            <div class="content-wrapper">
                <div class="container-fluid padding">
                    <div class="row welcome text-center">
                        <div class="col-12">
                            <h1 class="display-4">Safe Money Transfer</h1>
                        </div>
                        <hr />
                        <div class="col-12">
                            <p class="lead">
                                Welcome to our online money transaction website bKash.You can do
                                Send Money,Cash In,Cash Out,Mobile Recharge,Shopping Payment and
                                Paying Differents Bills through our website.
                            </p>
                        </div>
                    </div>
                </div>

                <!--- Three Column Section -->
                {% block content %}
                {% endblock  %}

            <footer id="contact">
                <div class="container-fluid padding">
                  <div class="row text-center">
                    <div class="col-12">
                      <h3>Contact Us</h3>
                    </div>
                    <div class="col-md-4">
                      <hr class="light" />
                      <i class="fas fa-phone mb-2"></i>
                      <h5>Mobile Number</h5>
                      <hr class="light" />
                      <p>+8801771369217</p>
                      <p>+8801521103929</p>
                    </div>
                    <div class="col-md-4">
                      <hr class="light" />
                      <i class="fas fa-laptop-house mb-2"></i>
                      <h5>Location</h5>
                      <hr class="light" />
                      <p>Room No : 219</p>
                      <p>Ahsanullah Hall</p>
                      <p>BUET,Dhaka</p>
                    </div>
                    <div class="col-md-4">
                      <hr class="light" />
                      <i class="far fa-envelope mb-2"></i>
                      <h5>Email</h5>
                      <hr class="light" />
                      <p>asifahmedutsa@gmail.com</p>
                      <p>abdullahalnoman@gmail.com</p>
                    </div>
                    <div class="col-12">
                      <hr class="light-100" />
                      <h5>copyright&copy;bKash.com</h5>
                    </div>
                  </div>
                </div>
              </footer>
          

        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <script>
            $(document).ready(function () {
                $("#sidebarCollapse").on("click", function () {
                    $("#sidebar").toggleClass("active");
                });
            });
        </script>

{% endif %}
</body>

</html>

bkash/services/templates/services/genericBlock2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'home/css/merchantStyle.css' %}" />
  <script src="https://kit.fontawesome.com/e367819fd5.js" crossorigin="anonymous"></script>

  <title>Merchant Home</title>
</head>

<body>
  <div class="wrapper">
    <nav id="sidebar">
      <div class="sidebar-header">
        <!--<h3>BOOTSTRAP SIDEBAR</h3>-->
        <div class="py-2 px-2 mb-2">
          <div class="media d-flex align-items-center justify-content-center">
            <img
              src="{{PHOTO}}?lastmod=12345678"
              alt="" width="100" height="100" class="mr-3 rounded-circle img-thumbnail shadow-sm" />
            <div class="media-body">
              <h5 class="m-0">{{NAME}}</h5>
              <p class="font-weight-normal mb-0" style="color: rgb(110, 243, 22);">Merchant</p>
            </div>
          </div>
          <div class="text-left">
            <p class="font-weight-bold pr-2 pt-1" style="color: rgb(173, 231, 13);">Head Office:</p>
            <p class="text-white font-weight-bold">{{HEAD_OFFICE_LOCATION}}</p>
          </div>
          <div class="text-left">
            <p class="font-weight-bold pr-2 pt-1" style="color: rgb(173, 231, 13);">Trade License No:</p>
            <p class="text-white font-weight-bold">{{TRADE_LICENSE_NO}}</p>
          </div>
        </div>
      </div>

      <ul class="list-unstyled components">
        <li>
          <a href="#balanceSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Cuurent
            Offer</a>
          <ul class="collapse list-unstyled" id="balanceSubmenu">
            <li class="text-center">
              <p class="pb-1 font-weight-bold" style="color: rgb(15, 51, 3)">
                {{OFFER_PERCENT}}% CASH_BACK 
              </p>
            </li>
          </ul>
        </li>
        <li>
          <a href="{% url 'home:home' %}">Home</a>
        </li>
        <li>
          <a href="{% url 'home:addBranch' %}">Add New Branch</a>
        </li>
        <li>
          <a href="#addOffer" data-toggle="modal" data-target="#addOffer">Set New Offer</a>
        </li>
        <li>
          <a href="{% url 'services:history' %}">Transaction History</a>
        </li>
      </ul>

      <ul class="list-unstyled CTAs">
        <li>
          <a href="{% url 'home:logout' %}" class="download">Logout</a>
        </li>
      </ul>
    </nav>


    <div class="content">

      <!--Navigation Bar with Icon-->
      <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
        <button type="button" id="sidebarCollapse" class="btn btn-info">
          <i class="fa fa-align-justify"></i>
        </button>
        <a href="" class="navbar-brand"><img src="{% static 'home/img/icon.png' %}" alt=""
            style="max-width: 50%; max-height: 50%; object-fit: contain" class="px-3" /></a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <div class="media d-flex align-items-center justify-content-center">
                <a href="" class="nav-link">
                  <img
                    src="{{PHOTO}}?lastmod=12345678"
                    alt="" width="50" height="50" style="object-fit: contain"
                    class="mr-3 rounded-circle img-thumbnail shadow-sm" />
                </a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

      <!--Main Content-->

      <!-- Modal -->
      <div class="modal fade" id="addOffer" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">SET YOUR CASHBACK OFFER PERCENTAGE</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <label for="offer">Enter Your Offer percent for customer in bKash payment</label>
                  <input type="number" id="offer" name="offer" class="form-control" min="0" max="30">
                  <br>
                  <input type="submit" class="btn btn-success pb-1" value="Submit">
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>

      <!--table of branch name-->
        {% block content %}
        {% endblock  %}

      <!-- Button To add Offer

      <div class="row p-1">
        <div class="col-md-12 text-right">
          <button class="btn btn-success badge-pill" data-toggle="modal" data-target="#addOffer">
            Add Offer
          </button>
        </div>
      </div>
    </div> -->
            <footer id="contact">
                <div class="container-fluid padding">
                  <div class="row text-center">
                    <div class="col-12">
                      <h3>Contact Us</h3>
                    </div>
                    <div class="col-md-4">
                      <hr class="light" />
                      <i class="fas fa-phone mb-2"></i>
                      <h5>Mobile Number</h5>
                      <hr class="light" />
                      <p>+8801771369217</p>
                      <p>+8801521103929</p>
                    </div>
                    <div class="col-md-4">
                      <hr class="light" />
                      <i class="fas fa-laptop-house mb-2"></i>
                      <h5>Location</h5>
                      <hr class="light" />
                      <p>Room No : 219</p>
                      <p>Ahsanullah Hall</p>
                      <p>BUET,Dhaka</p>
                    </div>
                    <div class="col-md-4">
                      <hr class="light" />
                      <i class="far fa-envelope mb-2"></i>
                      <h5>Email</h5>
                      <hr class="light" />
                      <p>asifahmedutsa@gmail.com</p>
                      <p>abdullahalnoman@gmail.com</p>
                    </div>
                    <div class="col-12">
                      <hr class="light-100" />
                      <h5>copyright&copy;bKash.com</h5>
                    </div>
                  </div>
                </div>
              </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script>
      $(document).ready(function () {
        $("#sidebarCollapse").on("click", function () {
          $("#sidebar").toggleClass("active");
        });
      });
    </script>
</body>

</html>

bkash/services/templates/services/history.html
{% extends 'services/genericBlock.html' %}

{% block content %}
    {% if NAME %}
        {% for hist in HISTORY %}
        <div class="card-body" style="border-color: rgb(66, 57, 57); border-radius: 5px; border-style: solid; width:80%; margin: auto;">
            <table class="table table-borderless text-center">
              <tbody>
                <tr>
                  <td style="text-align:left;"><b>{{hist.HIS_TYPE}}</b></td>
                  <td class="align-middle"></td>
                  <td style="text-align:right">{{hist.TIME}}</td>
                </tr>
                <tr>
                {% if MOBILE == hist.SENDER %} 
                    <td style="text-align:left;"><span style="color:red;">To: </span>{{hist.RECEIVER}}</td>
                {% else %}
                    <td style="text-align:left;"><span style="color:green;">From: </span>{{hist.SENDER}}</td>
                {% endif %}
                    <td class="align-middle">
                    </td>
                    <td style="text-align:right">
                    {% if hist.Billing_Id %}
                    <span style="font-family: cursive;">Billing ID: {{hist.Billing_Id}}</span>
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td style="text-align:left;">Txid: {{hist.TXID}}</td>
                    <td class="align-middle">
                    </td>
                {% if MOBILE == hist.SENDER %} 
                    <td style="text-align:right"><span style="color:red;">-{{hist.AMOUNT}}</span><i class="fas fa-dollar-sign"></i></td>
                {% else %}
                    <td style="text-align:right"><span style="color:green;">+{{hist.AMOUNT}}</span><i class="fas fa-dollar-sign"></i></td>
                {% endif %}
                </tr>
              </tbody>
            </table>
          </div>
        <p></p>
        <p></p>
        {% endfor %}
    {% endif %}
{% endblock %}